// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: humans/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetFeeBalanceRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetFeeBalanceRequest) Reset()         { *m = QueryGetFeeBalanceRequest{} }
func (m *QueryGetFeeBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetFeeBalanceRequest) ProtoMessage()    {}
func (*QueryGetFeeBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{2}
}
func (m *QueryGetFeeBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFeeBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFeeBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFeeBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFeeBalanceRequest.Merge(m, src)
}
func (m *QueryGetFeeBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFeeBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFeeBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFeeBalanceRequest proto.InternalMessageInfo

func (m *QueryGetFeeBalanceRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetFeeBalanceResponse struct {
	FeeBalance FeeBalance `protobuf:"bytes,1,opt,name=feeBalance,proto3" json:"feeBalance"`
}

func (m *QueryGetFeeBalanceResponse) Reset()         { *m = QueryGetFeeBalanceResponse{} }
func (m *QueryGetFeeBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetFeeBalanceResponse) ProtoMessage()    {}
func (*QueryGetFeeBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{3}
}
func (m *QueryGetFeeBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFeeBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFeeBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFeeBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFeeBalanceResponse.Merge(m, src)
}
func (m *QueryGetFeeBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFeeBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFeeBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFeeBalanceResponse proto.InternalMessageInfo

func (m *QueryGetFeeBalanceResponse) GetFeeBalance() FeeBalance {
	if m != nil {
		return m.FeeBalance
	}
	return FeeBalance{}
}

type QueryAllFeeBalanceRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFeeBalanceRequest) Reset()         { *m = QueryAllFeeBalanceRequest{} }
func (m *QueryAllFeeBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllFeeBalanceRequest) ProtoMessage()    {}
func (*QueryAllFeeBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{4}
}
func (m *QueryAllFeeBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFeeBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFeeBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFeeBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFeeBalanceRequest.Merge(m, src)
}
func (m *QueryAllFeeBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFeeBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFeeBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFeeBalanceRequest proto.InternalMessageInfo

func (m *QueryAllFeeBalanceRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllFeeBalanceResponse struct {
	FeeBalance []FeeBalance        `protobuf:"bytes,1,rep,name=feeBalance,proto3" json:"feeBalance"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFeeBalanceResponse) Reset()         { *m = QueryAllFeeBalanceResponse{} }
func (m *QueryAllFeeBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllFeeBalanceResponse) ProtoMessage()    {}
func (*QueryAllFeeBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{5}
}
func (m *QueryAllFeeBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFeeBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFeeBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFeeBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFeeBalanceResponse.Merge(m, src)
}
func (m *QueryAllFeeBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFeeBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFeeBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFeeBalanceResponse proto.InternalMessageInfo

func (m *QueryAllFeeBalanceResponse) GetFeeBalance() []FeeBalance {
	if m != nil {
		return m.FeeBalance
	}
	return nil
}

func (m *QueryAllFeeBalanceResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetKeysignVoteDataRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetKeysignVoteDataRequest) Reset()         { *m = QueryGetKeysignVoteDataRequest{} }
func (m *QueryGetKeysignVoteDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetKeysignVoteDataRequest) ProtoMessage()    {}
func (*QueryGetKeysignVoteDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{6}
}
func (m *QueryGetKeysignVoteDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKeysignVoteDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKeysignVoteDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKeysignVoteDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKeysignVoteDataRequest.Merge(m, src)
}
func (m *QueryGetKeysignVoteDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKeysignVoteDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKeysignVoteDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKeysignVoteDataRequest proto.InternalMessageInfo

func (m *QueryGetKeysignVoteDataRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetKeysignVoteDataResponse struct {
	KeysignVoteData KeysignVoteData `protobuf:"bytes,1,opt,name=keysignVoteData,proto3" json:"keysignVoteData"`
}

func (m *QueryGetKeysignVoteDataResponse) Reset()         { *m = QueryGetKeysignVoteDataResponse{} }
func (m *QueryGetKeysignVoteDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetKeysignVoteDataResponse) ProtoMessage()    {}
func (*QueryGetKeysignVoteDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{7}
}
func (m *QueryGetKeysignVoteDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKeysignVoteDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKeysignVoteDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKeysignVoteDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKeysignVoteDataResponse.Merge(m, src)
}
func (m *QueryGetKeysignVoteDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKeysignVoteDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKeysignVoteDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKeysignVoteDataResponse proto.InternalMessageInfo

func (m *QueryGetKeysignVoteDataResponse) GetKeysignVoteData() KeysignVoteData {
	if m != nil {
		return m.KeysignVoteData
	}
	return KeysignVoteData{}
}

type QueryAllKeysignVoteDataRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKeysignVoteDataRequest) Reset()         { *m = QueryAllKeysignVoteDataRequest{} }
func (m *QueryAllKeysignVoteDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllKeysignVoteDataRequest) ProtoMessage()    {}
func (*QueryAllKeysignVoteDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{8}
}
func (m *QueryAllKeysignVoteDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKeysignVoteDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKeysignVoteDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKeysignVoteDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKeysignVoteDataRequest.Merge(m, src)
}
func (m *QueryAllKeysignVoteDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKeysignVoteDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKeysignVoteDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKeysignVoteDataRequest proto.InternalMessageInfo

func (m *QueryAllKeysignVoteDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllKeysignVoteDataResponse struct {
	KeysignVoteData []KeysignVoteData   `protobuf:"bytes,1,rep,name=keysignVoteData,proto3" json:"keysignVoteData"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKeysignVoteDataResponse) Reset()         { *m = QueryAllKeysignVoteDataResponse{} }
func (m *QueryAllKeysignVoteDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllKeysignVoteDataResponse) ProtoMessage()    {}
func (*QueryAllKeysignVoteDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{9}
}
func (m *QueryAllKeysignVoteDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKeysignVoteDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKeysignVoteDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKeysignVoteDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKeysignVoteDataResponse.Merge(m, src)
}
func (m *QueryAllKeysignVoteDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKeysignVoteDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKeysignVoteDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKeysignVoteDataResponse proto.InternalMessageInfo

func (m *QueryAllKeysignVoteDataResponse) GetKeysignVoteData() []KeysignVoteData {
	if m != nil {
		return m.KeysignVoteData
	}
	return nil
}

func (m *QueryAllKeysignVoteDataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetObserveVoteRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetObserveVoteRequest) Reset()         { *m = QueryGetObserveVoteRequest{} }
func (m *QueryGetObserveVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetObserveVoteRequest) ProtoMessage()    {}
func (*QueryGetObserveVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{10}
}
func (m *QueryGetObserveVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetObserveVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetObserveVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetObserveVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetObserveVoteRequest.Merge(m, src)
}
func (m *QueryGetObserveVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetObserveVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetObserveVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetObserveVoteRequest proto.InternalMessageInfo

func (m *QueryGetObserveVoteRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetObserveVoteResponse struct {
	ObserveVote ObserveVote `protobuf:"bytes,1,opt,name=observeVote,proto3" json:"observeVote"`
}

func (m *QueryGetObserveVoteResponse) Reset()         { *m = QueryGetObserveVoteResponse{} }
func (m *QueryGetObserveVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetObserveVoteResponse) ProtoMessage()    {}
func (*QueryGetObserveVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{11}
}
func (m *QueryGetObserveVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetObserveVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetObserveVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetObserveVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetObserveVoteResponse.Merge(m, src)
}
func (m *QueryGetObserveVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetObserveVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetObserveVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetObserveVoteResponse proto.InternalMessageInfo

func (m *QueryGetObserveVoteResponse) GetObserveVote() ObserveVote {
	if m != nil {
		return m.ObserveVote
	}
	return ObserveVote{}
}

type QueryAllObserveVoteRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllObserveVoteRequest) Reset()         { *m = QueryAllObserveVoteRequest{} }
func (m *QueryAllObserveVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllObserveVoteRequest) ProtoMessage()    {}
func (*QueryAllObserveVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{12}
}
func (m *QueryAllObserveVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllObserveVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllObserveVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllObserveVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllObserveVoteRequest.Merge(m, src)
}
func (m *QueryAllObserveVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllObserveVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllObserveVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllObserveVoteRequest proto.InternalMessageInfo

func (m *QueryAllObserveVoteRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllObserveVoteResponse struct {
	ObserveVote []ObserveVote       `protobuf:"bytes,1,rep,name=observeVote,proto3" json:"observeVote"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllObserveVoteResponse) Reset()         { *m = QueryAllObserveVoteResponse{} }
func (m *QueryAllObserveVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllObserveVoteResponse) ProtoMessage()    {}
func (*QueryAllObserveVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd2e88e384104b5, []int{13}
}
func (m *QueryAllObserveVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllObserveVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllObserveVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllObserveVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllObserveVoteResponse.Merge(m, src)
}
func (m *QueryAllObserveVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllObserveVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllObserveVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllObserveVoteResponse proto.InternalMessageInfo

func (m *QueryAllObserveVoteResponse) GetObserveVote() []ObserveVote {
	if m != nil {
		return m.ObserveVote
	}
	return nil
}

func (m *QueryAllObserveVoteResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "humansdotai.humans.humans.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "humansdotai.humans.humans.QueryParamsResponse")
	proto.RegisterType((*QueryGetFeeBalanceRequest)(nil), "humansdotai.humans.humans.QueryGetFeeBalanceRequest")
	proto.RegisterType((*QueryGetFeeBalanceResponse)(nil), "humansdotai.humans.humans.QueryGetFeeBalanceResponse")
	proto.RegisterType((*QueryAllFeeBalanceRequest)(nil), "humansdotai.humans.humans.QueryAllFeeBalanceRequest")
	proto.RegisterType((*QueryAllFeeBalanceResponse)(nil), "humansdotai.humans.humans.QueryAllFeeBalanceResponse")
	proto.RegisterType((*QueryGetKeysignVoteDataRequest)(nil), "humansdotai.humans.humans.QueryGetKeysignVoteDataRequest")
	proto.RegisterType((*QueryGetKeysignVoteDataResponse)(nil), "humansdotai.humans.humans.QueryGetKeysignVoteDataResponse")
	proto.RegisterType((*QueryAllKeysignVoteDataRequest)(nil), "humansdotai.humans.humans.QueryAllKeysignVoteDataRequest")
	proto.RegisterType((*QueryAllKeysignVoteDataResponse)(nil), "humansdotai.humans.humans.QueryAllKeysignVoteDataResponse")
	proto.RegisterType((*QueryGetObserveVoteRequest)(nil), "humansdotai.humans.humans.QueryGetObserveVoteRequest")
	proto.RegisterType((*QueryGetObserveVoteResponse)(nil), "humansdotai.humans.humans.QueryGetObserveVoteResponse")
	proto.RegisterType((*QueryAllObserveVoteRequest)(nil), "humansdotai.humans.humans.QueryAllObserveVoteRequest")
	proto.RegisterType((*QueryAllObserveVoteResponse)(nil), "humansdotai.humans.humans.QueryAllObserveVoteResponse")
}

func init() { proto.RegisterFile("humans/query.proto", fileDescriptor_4fd2e88e384104b5) }

var fileDescriptor_4fd2e88e384104b5 = []byte{
	// 777 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xcf, 0x4e, 0xdb, 0x4e,
	0x10, 0xc7, 0xb3, 0xf0, 0x03, 0x89, 0x45, 0xbf, 0x22, 0x2d, 0x1c, 0xc0, 0xad, 0x4c, 0x71, 0x55,
	0xfe, 0x89, 0xda, 0x0d, 0xa5, 0xa9, 0xa8, 0x2a, 0x55, 0xa0, 0x0a, 0x0e, 0x48, 0x2d, 0xcd, 0x81,
	0x03, 0x17, 0xb4, 0x49, 0x16, 0x63, 0xe1, 0x78, 0x43, 0xbc, 0x41, 0xa0, 0x8a, 0x4b, 0x9f, 0xa0,
	0x6a, 0x5f, 0xa3, 0x87, 0xb6, 0x52, 0x7b, 0xef, 0x05, 0x71, 0x44, 0xea, 0xa5, 0xa7, 0xaa, 0x82,
	0xbe, 0x43, 0xaf, 0x55, 0x76, 0x27, 0xb1, 0x93, 0xd8, 0x8e, 0x81, 0x9c, 0xe2, 0xec, 0xec, 0xcc,
	0x7c, 0xbe, 0x33, 0xeb, 0x59, 0x63, 0xb2, 0x57, 0x2b, 0x53, 0xcf, 0xb7, 0x0e, 0x6a, 0xac, 0x7a,
	0x6c, 0x56, 0xaa, 0x5c, 0x70, 0x32, 0xa1, 0xd6, 0x4a, 0x5c, 0x50, 0xc7, 0x54, 0xcf, 0xf0, 0xa3,
	0x8d, 0xd9, 0xdc, 0xe6, 0x72, 0x97, 0x55, 0x7f, 0x52, 0x0e, 0xda, 0x1d, 0x9b, 0x73, 0xdb, 0x65,
	0x16, 0xad, 0x38, 0x16, 0xf5, 0x3c, 0x2e, 0xa8, 0x70, 0xb8, 0xe7, 0x83, 0x75, 0xbe, 0xc8, 0xfd,
	0x32, 0xf7, 0xad, 0x02, 0xf5, 0x99, 0xca, 0x63, 0x1d, 0x66, 0x0b, 0x4c, 0xd0, 0xac, 0x55, 0xa1,
	0xb6, 0xe3, 0xc9, 0xcd, 0xb0, 0x77, 0x14, 0x70, 0x2a, 0xb4, 0x4a, 0xcb, 0x8d, 0x00, 0xe3, 0xb0,
	0xb8, 0xcb, 0xd8, 0x4e, 0x81, 0xba, 0xd4, 0x2b, 0x32, 0xb0, 0xe8, 0x60, 0xd9, 0x67, 0xc7, 0xbe,
	0x63, 0x7b, 0x3b, 0x87, 0x5c, 0xb0, 0x9d, 0x12, 0x15, 0x14, 0xec, 0xa0, 0xc4, 0xe2, 0x05, 0x9f,
	0x55, 0x0f, 0x99, 0xb4, 0x2b, 0x93, 0x31, 0x86, 0xc9, 0xeb, 0x3a, 0xcb, 0xa6, 0xcc, 0x94, 0x67,
	0x07, 0x35, 0xe6, 0x0b, 0x63, 0x0b, 0x8f, 0xb6, 0xac, 0xfa, 0x15, 0xee, 0xf9, 0x8c, 0x3c, 0xc7,
	0x83, 0x8a, 0x68, 0x1c, 0xdd, 0x45, 0xb3, 0xc3, 0x8b, 0x53, 0x66, 0x6c, 0x89, 0x4c, 0xe5, 0xba,
	0xfa, 0xdf, 0xd9, 0xaf, 0xc9, 0x4c, 0x1e, 0xdc, 0x8c, 0x2c, 0x9e, 0x90, 0x71, 0xd7, 0x99, 0x58,
	0x63, 0x6c, 0x55, 0x89, 0x80, 0xa4, 0x64, 0x0c, 0x0f, 0x38, 0x5e, 0x89, 0x1d, 0xc9, 0xe0, 0x43,
	0x79, 0xf5, 0xc7, 0x70, 0xb0, 0x16, 0xe5, 0x02, 0x44, 0x1b, 0x18, 0xef, 0x36, 0x57, 0x81, 0xea,
	0x7e, 0x02, 0x55, 0x10, 0x02, 0xc8, 0x42, 0xee, 0x46, 0x11, 0xe8, 0x56, 0x5c, 0xb7, 0x93, 0x6e,
	0x0d, 0xe3, 0xa0, 0x4d, 0x90, 0x69, 0xda, 0x54, 0x3d, 0x35, 0xeb, 0x3d, 0x35, 0xd5, 0xd9, 0x81,
	0x9e, 0x9a, 0x9b, 0xd4, 0x6e, 0xf8, 0xe6, 0x43, 0x9e, 0xc6, 0x17, 0x04, 0x82, 0xda, 0xb2, 0xc4,
	0x08, 0xea, 0xbf, 0x81, 0x20, 0xb2, 0xde, 0xc2, 0xdc, 0x27, 0x99, 0x67, 0xba, 0x32, 0x2b, 0x92,
	0x16, 0xe8, 0x1c, 0xd6, 0x1b, 0x4d, 0xd8, 0x50, 0x67, 0x6c, 0x8b, 0x0b, 0xf6, 0x82, 0x0a, 0x9a,
	0xdc, 0xbc, 0x13, 0x3c, 0x19, 0xeb, 0x07, 0x82, 0xb7, 0xf1, 0xc8, 0x7e, 0xab, 0x09, 0x8a, 0x3b,
	0x9f, 0xa0, 0xba, 0x2d, 0x18, 0x48, 0x6f, 0x0f, 0x64, 0xec, 0x01, 0xf6, 0x8a, 0xeb, 0xc6, 0x60,
	0xf7, 0xaa, 0xab, 0xa7, 0x08, 0x94, 0x46, 0xa5, 0x4a, 0x52, 0xda, 0xdf, 0x13, 0xa5, 0xbd, 0xeb,
	0xf4, 0x62, 0xf0, 0xba, 0xbd, 0x52, 0xd3, 0xa2, 0x9e, 0x23, 0xb9, 0xcb, 0x65, 0x7c, 0x3b, 0xd2,
	0x07, 0x74, 0xbf, 0xc4, 0xc3, 0x3c, 0x58, 0x6e, 0x16, 0x39, 0x5e, 0x73, 0x28, 0x08, 0xe8, 0x0d,
	0x07, 0x30, 0x4a, 0xc1, 0x0b, 0x14, 0x81, 0xd8, 0xab, 0x8e, 0x7e, 0x43, 0xa0, 0xaa, 0x3d, 0x4d,
	0x9c, 0xaa, 0xfe, 0x1b, 0xa9, 0xea, 0x59, 0x07, 0x17, 0xff, 0x0e, 0xe1, 0x01, 0x09, 0x4e, 0xde,
	0x23, 0x3c, 0xa8, 0xc6, 0x30, 0x79, 0x90, 0x00, 0xd6, 0x39, 0xff, 0x35, 0x33, 0xed, 0x76, 0x95,
	0xdf, 0x98, 0x7b, 0xfb, 0xe3, 0xcf, 0x87, 0xbe, 0x7b, 0x64, 0xca, 0x0a, 0xf9, 0xc1, 0xb3, 0xd5,
	0x72, 0x97, 0x91, 0xcf, 0x08, 0xe3, 0x60, 0x68, 0x91, 0xa5, 0x6e, 0x99, 0xa2, 0xae, 0x0a, 0xed,
	0xf1, 0x15, 0xbd, 0x00, 0x33, 0x27, 0x31, 0x1f, 0x12, 0x33, 0x01, 0x33, 0x74, 0xbb, 0x5a, 0x6f,
	0xe4, 0xf9, 0x3e, 0x21, 0x1f, 0x11, 0xfe, 0x3f, 0x08, 0xb7, 0xe2, 0xba, 0xdd, 0xb1, 0xa3, 0xee,
	0x90, 0xee, 0xd8, 0x91, 0x77, 0x82, 0x61, 0x4a, 0xec, 0x59, 0x32, 0x9d, 0x0e, 0x9b, 0x9c, 0x22,
	0x3c, 0xd2, 0x36, 0x37, 0xc8, 0x72, 0x8a, 0x8a, 0x45, 0xcf, 0x48, 0xed, 0xe9, 0x75, 0x5c, 0x01,
	0xfd, 0x99, 0x44, 0xcf, 0x91, 0xa5, 0x04, 0xf4, 0x8e, 0xaf, 0x96, 0x66, 0xdd, 0xbf, 0x23, 0x4c,
	0xda, 0x22, 0xd7, 0x8b, 0xbf, 0x9c, 0xa2, 0x8c, 0xd7, 0xd5, 0x12, 0x3f, 0xbf, 0x8d, 0x25, 0xa9,
	0xc5, 0x24, 0x0b, 0x57, 0xd1, 0x42, 0xbe, 0x22, 0x3c, 0x1c, 0x7a, 0xf5, 0x49, 0x9a, 0xa3, 0xdb,
	0x39, 0xd6, 0xb4, 0xdc, 0x55, 0xdd, 0x00, 0xfa, 0x89, 0x84, 0xce, 0x12, 0x2b, 0x01, 0x3a, 0xfc,
	0x59, 0xd8, 0xac, 0xfd, 0x27, 0x84, 0x6f, 0x85, 0x02, 0xd6, 0xeb, 0x9e, 0xe6, 0xf8, 0x5e, 0x07,
	0x3d, 0x7a, 0xc2, 0x1a, 0x96, 0x44, 0x9f, 0x23, 0x33, 0x29, 0xd1, 0x57, 0xd7, 0xce, 0x2e, 0x74,
	0x74, 0x7e, 0xa1, 0xa3, 0xdf, 0x17, 0x3a, 0x7a, 0x77, 0xa9, 0x67, 0xce, 0x2f, 0xf5, 0xcc, 0xcf,
	0x4b, 0x3d, 0xb3, 0xbd, 0x60, 0x3b, 0x62, 0xaf, 0x56, 0x30, 0x8b, 0xbc, 0x1c, 0x15, 0xec, 0xa8,
	0xf1, 0x20, 0x8e, 0x2b, 0xcc, 0x2f, 0x0c, 0xca, 0x4f, 0xe3, 0x47, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x53, 0x0e, 0xae, 0x4a, 0x15, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a FeeBalance by index.
	FeeBalance(ctx context.Context, in *QueryGetFeeBalanceRequest, opts ...grpc.CallOption) (*QueryGetFeeBalanceResponse, error)
	// Queries a list of FeeBalance items.
	FeeBalanceAll(ctx context.Context, in *QueryAllFeeBalanceRequest, opts ...grpc.CallOption) (*QueryAllFeeBalanceResponse, error)
	// Queries a KeysignVoteData by index.
	KeysignVoteData(ctx context.Context, in *QueryGetKeysignVoteDataRequest, opts ...grpc.CallOption) (*QueryGetKeysignVoteDataResponse, error)
	// Queries a list of KeysignVoteData items.
	KeysignVoteDataAll(ctx context.Context, in *QueryAllKeysignVoteDataRequest, opts ...grpc.CallOption) (*QueryAllKeysignVoteDataResponse, error)
	// Queries a ObserveVote by index.
	ObserveVote(ctx context.Context, in *QueryGetObserveVoteRequest, opts ...grpc.CallOption) (*QueryGetObserveVoteResponse, error)
	// Queries a list of ObserveVote items.
	ObserveVoteAll(ctx context.Context, in *QueryAllObserveVoteRequest, opts ...grpc.CallOption) (*QueryAllObserveVoteResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/humansdotai.humans.humans.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FeeBalance(ctx context.Context, in *QueryGetFeeBalanceRequest, opts ...grpc.CallOption) (*QueryGetFeeBalanceResponse, error) {
	out := new(QueryGetFeeBalanceResponse)
	err := c.cc.Invoke(ctx, "/humansdotai.humans.humans.Query/FeeBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FeeBalanceAll(ctx context.Context, in *QueryAllFeeBalanceRequest, opts ...grpc.CallOption) (*QueryAllFeeBalanceResponse, error) {
	out := new(QueryAllFeeBalanceResponse)
	err := c.cc.Invoke(ctx, "/humansdotai.humans.humans.Query/FeeBalanceAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeysignVoteData(ctx context.Context, in *QueryGetKeysignVoteDataRequest, opts ...grpc.CallOption) (*QueryGetKeysignVoteDataResponse, error) {
	out := new(QueryGetKeysignVoteDataResponse)
	err := c.cc.Invoke(ctx, "/humansdotai.humans.humans.Query/KeysignVoteData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeysignVoteDataAll(ctx context.Context, in *QueryAllKeysignVoteDataRequest, opts ...grpc.CallOption) (*QueryAllKeysignVoteDataResponse, error) {
	out := new(QueryAllKeysignVoteDataResponse)
	err := c.cc.Invoke(ctx, "/humansdotai.humans.humans.Query/KeysignVoteDataAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ObserveVote(ctx context.Context, in *QueryGetObserveVoteRequest, opts ...grpc.CallOption) (*QueryGetObserveVoteResponse, error) {
	out := new(QueryGetObserveVoteResponse)
	err := c.cc.Invoke(ctx, "/humansdotai.humans.humans.Query/ObserveVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ObserveVoteAll(ctx context.Context, in *QueryAllObserveVoteRequest, opts ...grpc.CallOption) (*QueryAllObserveVoteResponse, error) {
	out := new(QueryAllObserveVoteResponse)
	err := c.cc.Invoke(ctx, "/humansdotai.humans.humans.Query/ObserveVoteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a FeeBalance by index.
	FeeBalance(context.Context, *QueryGetFeeBalanceRequest) (*QueryGetFeeBalanceResponse, error)
	// Queries a list of FeeBalance items.
	FeeBalanceAll(context.Context, *QueryAllFeeBalanceRequest) (*QueryAllFeeBalanceResponse, error)
	// Queries a KeysignVoteData by index.
	KeysignVoteData(context.Context, *QueryGetKeysignVoteDataRequest) (*QueryGetKeysignVoteDataResponse, error)
	// Queries a list of KeysignVoteData items.
	KeysignVoteDataAll(context.Context, *QueryAllKeysignVoteDataRequest) (*QueryAllKeysignVoteDataResponse, error)
	// Queries a ObserveVote by index.
	ObserveVote(context.Context, *QueryGetObserveVoteRequest) (*QueryGetObserveVoteResponse, error)
	// Queries a list of ObserveVote items.
	ObserveVoteAll(context.Context, *QueryAllObserveVoteRequest) (*QueryAllObserveVoteResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) FeeBalance(ctx context.Context, req *QueryGetFeeBalanceRequest) (*QueryGetFeeBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeeBalance not implemented")
}
func (*UnimplementedQueryServer) FeeBalanceAll(ctx context.Context, req *QueryAllFeeBalanceRequest) (*QueryAllFeeBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeeBalanceAll not implemented")
}
func (*UnimplementedQueryServer) KeysignVoteData(ctx context.Context, req *QueryGetKeysignVoteDataRequest) (*QueryGetKeysignVoteDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeysignVoteData not implemented")
}
func (*UnimplementedQueryServer) KeysignVoteDataAll(ctx context.Context, req *QueryAllKeysignVoteDataRequest) (*QueryAllKeysignVoteDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeysignVoteDataAll not implemented")
}
func (*UnimplementedQueryServer) ObserveVote(ctx context.Context, req *QueryGetObserveVoteRequest) (*QueryGetObserveVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObserveVote not implemented")
}
func (*UnimplementedQueryServer) ObserveVoteAll(ctx context.Context, req *QueryAllObserveVoteRequest) (*QueryAllObserveVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObserveVoteAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/humansdotai.humans.humans.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FeeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetFeeBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FeeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/humansdotai.humans.humans.Query/FeeBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FeeBalance(ctx, req.(*QueryGetFeeBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FeeBalanceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllFeeBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FeeBalanceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/humansdotai.humans.humans.Query/FeeBalanceAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FeeBalanceAll(ctx, req.(*QueryAllFeeBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeysignVoteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetKeysignVoteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeysignVoteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/humansdotai.humans.humans.Query/KeysignVoteData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeysignVoteData(ctx, req.(*QueryGetKeysignVoteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeysignVoteDataAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllKeysignVoteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeysignVoteDataAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/humansdotai.humans.humans.Query/KeysignVoteDataAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeysignVoteDataAll(ctx, req.(*QueryAllKeysignVoteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ObserveVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetObserveVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ObserveVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/humansdotai.humans.humans.Query/ObserveVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ObserveVote(ctx, req.(*QueryGetObserveVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ObserveVoteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllObserveVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ObserveVoteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/humansdotai.humans.humans.Query/ObserveVoteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ObserveVoteAll(ctx, req.(*QueryAllObserveVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "humansdotai.humans.humans.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "FeeBalance",
			Handler:    _Query_FeeBalance_Handler,
		},
		{
			MethodName: "FeeBalanceAll",
			Handler:    _Query_FeeBalanceAll_Handler,
		},
		{
			MethodName: "KeysignVoteData",
			Handler:    _Query_KeysignVoteData_Handler,
		},
		{
			MethodName: "KeysignVoteDataAll",
			Handler:    _Query_KeysignVoteDataAll_Handler,
		},
		{
			MethodName: "ObserveVote",
			Handler:    _Query_ObserveVote_Handler,
		},
		{
			MethodName: "ObserveVoteAll",
			Handler:    _Query_ObserveVoteAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "humans/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetFeeBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFeeBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFeeBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetFeeBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFeeBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFeeBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FeeBalance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllFeeBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFeeBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFeeBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllFeeBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFeeBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFeeBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FeeBalance) > 0 {
		for iNdEx := len(m.FeeBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetKeysignVoteDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKeysignVoteDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKeysignVoteDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetKeysignVoteDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKeysignVoteDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKeysignVoteDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.KeysignVoteData.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllKeysignVoteDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKeysignVoteDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKeysignVoteDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllKeysignVoteDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKeysignVoteDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKeysignVoteDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.KeysignVoteData) > 0 {
		for iNdEx := len(m.KeysignVoteData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeysignVoteData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetObserveVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetObserveVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetObserveVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetObserveVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetObserveVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetObserveVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ObserveVote.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllObserveVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllObserveVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllObserveVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllObserveVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllObserveVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllObserveVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ObserveVote) > 0 {
		for iNdEx := len(m.ObserveVote) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ObserveVote[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetFeeBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetFeeBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FeeBalance.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllFeeBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllFeeBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FeeBalance) > 0 {
		for _, e := range m.FeeBalance {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetKeysignVoteDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetKeysignVoteDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.KeysignVoteData.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllKeysignVoteDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllKeysignVoteDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.KeysignVoteData) > 0 {
		for _, e := range m.KeysignVoteData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetObserveVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetObserveVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObserveVote.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllObserveVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllObserveVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ObserveVote) > 0 {
		for _, e := range m.ObserveVote {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFeeBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFeeBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFeeBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFeeBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFeeBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFeeBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFeeBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFeeBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFeeBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFeeBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFeeBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFeeBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeBalance = append(m.FeeBalance, FeeBalance{})
			if err := m.FeeBalance[len(m.FeeBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKeysignVoteDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKeysignVoteDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKeysignVoteDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKeysignVoteDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKeysignVoteDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKeysignVoteDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeysignVoteData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.KeysignVoteData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKeysignVoteDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKeysignVoteDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKeysignVoteDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKeysignVoteDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKeysignVoteDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKeysignVoteDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeysignVoteData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeysignVoteData = append(m.KeysignVoteData, KeysignVoteData{})
			if err := m.KeysignVoteData[len(m.KeysignVoteData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetObserveVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetObserveVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetObserveVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetObserveVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetObserveVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetObserveVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObserveVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObserveVote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllObserveVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllObserveVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllObserveVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllObserveVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllObserveVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllObserveVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObserveVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObserveVote = append(m.ObserveVote, ObserveVote{})
			if err := m.ObserveVote[len(m.ObserveVote)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
